export const dentalMedicines = [
  {
    "id": "MED-DENT-0001",
    "name": "Dolo 650",
    "generic": "Paracetamol / Acetaminophen",
    "description": "500 mg / 650 mg | Tablet / Syrup / Drops | Pain/fever relief",
    "category": "Analgesic",
    "condition": "Tooth pain",
    "strength": "500 mg / 650 mg",
    "dosageForm": "Tablet / Syrup / Drops",
    "route": "Oral",
    "brand": "Dolo 650",
    "manufacturer": "Micro Labs",
    "prescriptionType": "OTC/Rx as per strength",
    "ageGroup": "Adult/Child",
    "pregnancyCaution": "Yes",
    "allergyCheckRequired": "Yes",
    "procedureOnly": "No",
    "antibioticFlag": "No",
    "otcFlag": "Yes",
    "showToPatient": "Yes",
    "commonUse": "Pain/fever relief",
    "safetyNotes": "Check liver disease, alcohol use, overdose risk.",
    "sourceUrl": "https://www.1mg.com/search/all?name=dolo%20650",
    "status": "Active"
  },
  {
    "id": "MED-DENT-0002",
    "name": "Calpol",
    "generic": "Paracetamol",
    "description": "120 mg/5 ml syrup sample | Tablet / Syrup | Pediatric/adult pain relief",
    "category": "Analgesic",
    "condition": "Tooth pain",
    "strength": "120 mg/5 ml syrup sample",
    "dosageForm": "Tablet / Syrup",
    "route": "Oral",
    "brand": "Calpol",
    "manufacturer": "Haleon / GSK brand",
    "prescriptionType": "OTC/Rx as per strength",
    "ageGroup": "Adult/Child",
    "pregnancyCaution": "Yes",
    "allergyCheckRequired": "Yes",
    "procedureOnly": "No",
    "antibioticFlag": "No",
    "otcFlag": "Yes",
    "showToPatient": "Yes",
    "commonUse": "Pediatric/adult pain relief",
    "safetyNotes": "Use pediatric medicines only as prescribed by doctor/dentist.",
    "sourceUrl": "https://www.1mg.com/search/all?name=calpol",
    "status": "Active"
  },
  {
    "id": "MED-DENT-0003",
    "name": "Brufen",
    "generic": "Ibuprofen",
    "description": "200 mg / 400 mg sample | Tablet / Suspension | Pain and inflammation",
    "category": "NSAID",
    "condition": "Tooth pain with swelling",
    "strength": "200 mg / 400 mg sample",
    "dosageForm": "Tablet / Suspension",
    "route": "Oral",
    "brand": "Brufen",
    "manufacturer": "Abbott",
    "prescriptionType": "Rx/OTC depends on market",
    "ageGroup": "Adult/Child",
    "pregnancyCaution": "Yes",
    "allergyCheckRequired": "Yes",
    "procedureOnly": "No",
    "antibioticFlag": "No",
    "otcFlag": "Yes",
    "showToPatient": "Yes",
    "commonUse": "Pain and inflammation",
    "safetyNotes": "Avoid in stomach ulcer, kidney disease, blood thinners, late pregnancy unless doctor approves.",
    "sourceUrl": "https://www.1mg.com/search/all?name=brufen",
    "status": "Active"
  },
  {
    "id": "MED-DENT-0004",
    "name": "Combiflam",
    "generic": "Ibuprofen + Paracetamol",
    "description": "400 mg + 325 mg sample | Tablet / Suspension | Pain and swelling",
    "category": "NSAID + Analgesic",
    "condition": "Tooth pain with swelling",
    "strength": "400 mg + 325 mg sample",
    "dosageForm": "Tablet / Suspension",
    "route": "Oral",
    "brand": "Combiflam",
    "manufacturer": "Sanofi Consumer Healthcare India",
    "prescriptionType": "Rx/OTC depends on strength",
    "ageGroup": "Adult/Child",
    "pregnancyCaution": "Yes",
    "allergyCheckRequired": "Yes",
    "procedureOnly": "No",
    "antibioticFlag": "No",
    "otcFlag": "Yes",
    "showToPatient": "Yes",
    "commonUse": "Pain and swelling",
    "safetyNotes": "Avoid duplicate paracetamol use and NSAID contraindications.",
    "sourceUrl": "https://www.1mg.com/generics/ibuprofen-paracetamol-401942",
    "status": "Active"
  },
  {
    "id": "MED-DENT-0005",
    "name": "Voveran",
    "generic": "Diclofenac",
    "description": "50 mg sample | Tablet / Injection / Gel | Pain and inflammation",
    "category": "NSAID",
    "condition": "Acute dental pain",
    "strength": "50 mg sample",
    "dosageForm": "Tablet / Injection / Gel",
    "route": "Oral/Injection/Topical",
    "brand": "Voveran",
    "manufacturer": "Novartis / Dr. Reddy's marketed variants",
    "prescriptionType": "Rx",
    "ageGroup": "Adult",
    "pregnancyCaution": "Yes",
    "allergyCheckRequired": "Yes",
    "procedureOnly": "No",
    "antibioticFlag": "No",
    "otcFlag": "No",
    "showToPatient": "Yes",
    "commonUse": "Pain and inflammation",
    "safetyNotes": "Use only with dentist/doctor advice; NSAID cautions apply.",
    "sourceUrl": "https://www.1mg.com/search/all?name=voveran",
    "status": "Active"
  },
  {
    "id": "MED-DENT-0006",
    "name": "Zerodol",
    "generic": "Aceclofenac",
    "description": "100 mg sample | Tablet | Pain and inflammation",
    "category": "NSAID",
    "condition": "Dental pain",
    "strength": "100 mg sample",
    "dosageForm": "Tablet",
    "route": "Oral",
    "brand": "Zerodol",
    "manufacturer": "IPCA Laboratories",
    "prescriptionType": "Rx",
    "ageGroup": "Adult",
    "pregnancyCaution": "Yes",
    "allergyCheckRequired": "Yes",
    "procedureOnly": "No",
    "antibioticFlag": "No",
    "otcFlag": "No",
    "showToPatient": "Yes",
    "commonUse": "Pain and inflammation",
    "safetyNotes": "Avoid in NSAID allergy, ulcer, kidney disease unless advised.",
    "sourceUrl": "https://www.1mg.com/search/all?name=zerodol",
    "status": "Active"
  },
  {
    "id": "MED-DENT-0007",
    "name": "Ketorol",
    "generic": "Ketorolac",
    "description": "10 mg sample | Tablet / Injection | Short-term severe pain",
    "category": "NSAID",
    "condition": "Severe dental pain",
    "strength": "10 mg sample",
    "dosageForm": "Tablet / Injection",
    "route": "Oral/Injection",
    "brand": "Ketorol",
    "manufacturer": "Dr. Reddy's",
    "prescriptionType": "Rx",
    "ageGroup": "Adult",
    "pregnancyCaution": "Yes",
    "allergyCheckRequired": "Yes",
    "procedureOnly": "No",
    "antibioticFlag": "No",
    "otcFlag": "No",
    "showToPatient": "Yes",
    "commonUse": "Short-term severe pain",
    "safetyNotes": "Short-term only; high GI/kidney caution.",
    "sourceUrl": "https://www.1mg.com/search/all?name=ketorol",
    "status": "Active"
  },
  {
    "id": "MED-DENT-0008",
    "name": "Mox",
    "generic": "Amoxicillin",
    "description": "250 mg / 500 mg sample | Capsule / Tablet / Dry Syrup | Dental infection where antibiotic is clinically indicated",
    "category": "Antibiotic",
    "condition": "Tooth infection / abscess",
    "strength": "250 mg / 500 mg sample",
    "dosageForm": "Capsule / Tablet / Dry Syrup",
    "route": "Oral",
    "brand": "Mox",
    "manufacturer": "Sun Pharma",
    "prescriptionType": "Rx only",
    "ageGroup": "Adult/Child",
    "pregnancyCaution": "Yes",
    "allergyCheckRequired": "Yes",
    "procedureOnly": "No",
    "antibioticFlag": "Yes",
    "otcFlag": "No",
    "showToPatient": "Yes",
    "commonUse": "Dental infection where antibiotic is clinically indicated",
    "safetyNotes": "Check penicillin allergy; dental procedure may still be required.",
    "sourceUrl": "https://www.1mg.com/search/all?name=mox%20amoxicillin",
    "status": "Active"
  },
  {
    "id": "MED-DENT-0009",
    "name": "Augmentin",
    "generic": "Amoxicillin + Clavulanic Acid",
    "description": "625 mg sample | Tablet / Dry Syrup / Injection | Broader dental infection coverage",
    "category": "Antibiotic",
    "condition": "Tooth infection / abscess",
    "strength": "625 mg sample",
    "dosageForm": "Tablet / Dry Syrup / Injection",
    "route": "Oral/Injection",
    "brand": "Augmentin",
    "manufacturer": "GlaxoSmithKline Pharmaceuticals",
    "prescriptionType": "Rx only",
    "ageGroup": "Adult/Child",
    "pregnancyCaution": "Yes",
    "allergyCheckRequired": "Yes",
    "procedureOnly": "No",
    "antibioticFlag": "Yes",
    "otcFlag": "No",
    "showToPatient": "Yes",
    "commonUse": "Broader dental infection coverage",
    "safetyNotes": "Prescription-only; check penicillin allergy; avoid unnecessary antibiotics.",
    "sourceUrl": "https://www.1mg.com/generics/amoxycillin-clavulanic-acid-400256",
    "status": "Active"
  },
  {
    "id": "MED-DENT-0010",
    "name": "Clavam",
    "generic": "Amoxicillin + Clavulanic Acid",
    "description": "625 mg sample | Tablet / Dry Syrup | Dental infection where indicated",
    "category": "Antibiotic",
    "condition": "Tooth infection / abscess",
    "strength": "625 mg sample",
    "dosageForm": "Tablet / Dry Syrup",
    "route": "Oral",
    "brand": "Clavam",
    "manufacturer": "Alkem Laboratories",
    "prescriptionType": "Rx only",
    "ageGroup": "Adult/Child",
    "pregnancyCaution": "Yes",
    "allergyCheckRequired": "Yes",
    "procedureOnly": "No",
    "antibioticFlag": "Yes",
    "otcFlag": "No",
    "showToPatient": "Yes",
    "commonUse": "Dental infection where indicated",
    "safetyNotes": "Prescription-only; check allergy and renal/liver history.",
    "sourceUrl": "https://www.1mg.com/search/all?name=clavam",
    "status": "Active"
  },
  {
    "id": "MED-DENT-0011",
    "name": "Moxikind-CV",
    "generic": "Amoxicillin + Clavulanic Acid",
    "description": "625 mg sample | Tablet / Dry Syrup | Dental infection where indicated",
    "category": "Antibiotic",
    "condition": "Tooth infection / abscess",
    "strength": "625 mg sample",
    "dosageForm": "Tablet / Dry Syrup",
    "route": "Oral",
    "brand": "Moxikind-CV",
    "manufacturer": "Mankind Pharma",
    "prescriptionType": "Rx only",
    "ageGroup": "Adult/Child",
    "pregnancyCaution": "Yes",
    "allergyCheckRequired": "Yes",
    "procedureOnly": "No",
    "antibioticFlag": "Yes",
    "otcFlag": "No",
    "showToPatient": "Yes",
    "commonUse": "Dental infection where indicated",
    "safetyNotes": "Prescription-only; check penicillin allergy.",
    "sourceUrl": "https://www.1mg.com/drugs/moxikind-cv-625-tablet-329310",
    "status": "Active"
  },
  {
    "id": "MED-DENT-0012",
    "name": "Metrogyl",
    "generic": "Metronidazole",
    "description": "400 mg sample | Tablet / Suspension / IV | Anaerobic infection support",
    "category": "Antibiotic",
    "condition": "Anaerobic dental infection",
    "strength": "400 mg sample",
    "dosageForm": "Tablet / Suspension / IV",
    "route": "Oral/Injection",
    "brand": "Metrogyl",
    "manufacturer": "J.B. Chemicals / marketed variants",
    "prescriptionType": "Rx only",
    "ageGroup": "Adult/Child",
    "pregnancyCaution": "Yes",
    "allergyCheckRequired": "Yes",
    "procedureOnly": "No",
    "antibioticFlag": "Yes",
    "otcFlag": "No",
    "showToPatient": "Yes",
    "commonUse": "Anaerobic infection support",
    "safetyNotes": "Avoid alcohol; dentist decides combination/need.",
    "sourceUrl": "https://www.1mg.com/search/all?name=metrogyl",
    "status": "Active"
  },
  {
    "id": "MED-DENT-0013",
    "name": "Various brands",
    "generic": "Amoxicillin + Metronidazole",
    "description": "Sample combination use | Tablet | Selected periodontal infection cases",
    "category": "Antibiotic combination",
    "condition": "Gum infection / periodontitis",
    "strength": "Sample combination use",
    "dosageForm": "Tablet",
    "route": "Oral",
    "brand": "Various brands",
    "manufacturer": "Various",
    "prescriptionType": "Rx only",
    "ageGroup": "Adult",
    "pregnancyCaution": "Yes",
    "allergyCheckRequired": "Yes",
    "procedureOnly": "No",
    "antibioticFlag": "Yes",
    "otcFlag": "No",
    "showToPatient": "Yes",
    "commonUse": "Selected periodontal infection cases",
    "safetyNotes": "Only after dentist evaluation; scaling/root planing is primary treatment.",
    "sourceUrl": "https://www.ada.org/resources/research/science/evidence-based-dental-research/antibiotics-for-dental-pain-and-swelling",
    "status": "Active"
  },
  {
    "id": "MED-DENT-0014",
    "name": "Azee",
    "generic": "Azithromycin",
    "description": "250 mg / 500 mg sample | Tablet / Suspension | Alternative antibiotic in selected allergy cases",
    "category": "Antibiotic",
    "condition": "Penicillin allergy infection",
    "strength": "250 mg / 500 mg sample",
    "dosageForm": "Tablet / Suspension",
    "route": "Oral",
    "brand": "Azee",
    "manufacturer": "Cipla",
    "prescriptionType": "Rx only",
    "ageGroup": "Adult/Child",
    "pregnancyCaution": "Yes",
    "allergyCheckRequired": "Yes",
    "procedureOnly": "No",
    "antibioticFlag": "Yes",
    "otcFlag": "No",
    "showToPatient": "Yes",
    "commonUse": "Alternative antibiotic in selected allergy cases",
    "safetyNotes": "Doctor/dentist to decide; check QT/cardiac history and interactions.",
    "sourceUrl": "https://www.1mg.com/search/all?name=azee",
    "status": "Active"
  },
  {
    "id": "MED-DENT-0015",
    "name": "Claribid",
    "generic": "Clarithromycin",
    "description": "250 mg / 500 mg sample | Tablet / Suspension | Alternative antibiotic in selected cases",
    "category": "Antibiotic",
    "condition": "Penicillin allergy infection",
    "strength": "250 mg / 500 mg sample",
    "dosageForm": "Tablet / Suspension",
    "route": "Oral",
    "brand": "Claribid",
    "manufacturer": "Abbott",
    "prescriptionType": "Rx only",
    "ageGroup": "Adult/Child",
    "pregnancyCaution": "Yes",
    "allergyCheckRequired": "Yes",
    "procedureOnly": "No",
    "antibioticFlag": "Yes",
    "otcFlag": "No",
    "showToPatient": "Yes",
    "commonUse": "Alternative antibiotic in selected cases",
    "safetyNotes": "Check interactions and cardiac/QT risk.",
    "sourceUrl": "https://www.1mg.com/search/all?name=claribid",
    "status": "Active"
  },
  {
    "id": "MED-DENT-0016",
    "name": "Dalacin C",
    "generic": "Clindamycin",
    "description": "150 mg / 300 mg sample | Capsule / Injection | Selected severe infection/allergy cases",
    "category": "Antibiotic",
    "condition": "Severe infection / allergy cases",
    "strength": "150 mg / 300 mg sample",
    "dosageForm": "Capsule / Injection",
    "route": "Oral/Injection",
    "brand": "Dalacin C",
    "manufacturer": "Pfizer",
    "prescriptionType": "Rx only",
    "ageGroup": "Adult",
    "pregnancyCaution": "Yes",
    "allergyCheckRequired": "Yes",
    "procedureOnly": "No",
    "antibioticFlag": "Yes",
    "otcFlag": "No",
    "showToPatient": "Yes",
    "commonUse": "Selected severe infection/allergy cases",
    "safetyNotes": "C. difficile/diarrhea risk; strict prescription use.",
    "sourceUrl": "https://www.1mg.com/search/all?name=dalacin%20c",
    "status": "Active"
  },
  {
    "id": "MED-DENT-0017",
    "name": "Hexidine",
    "generic": "Chlorhexidine Gluconate",
    "description": "0.2% sample | Mouthwash | Gum infection/plaque control",
    "category": "Antiseptic mouthwash",
    "condition": "Gum disease / gingivitis",
    "strength": "0.2% sample",
    "dosageForm": "Mouthwash",
    "route": "Oral rinse",
    "brand": "Hexidine",
    "manufacturer": "ICPA Health Products",
    "prescriptionType": "Dentist advised",
    "ageGroup": "Adult/Child as advised",
    "pregnancyCaution": "Yes",
    "allergyCheckRequired": "Yes",
    "procedureOnly": "No",
    "antibioticFlag": "No",
    "otcFlag": "No",
    "showToPatient": "Yes",
    "commonUse": "Gum infection/plaque control",
    "safetyNotes": "Short-term use; may stain teeth; do not swallow.",
    "sourceUrl": "https://www.1mg.com/search/all?name=hexidine",
    "status": "Active"
  },
  {
    "id": "MED-DENT-0018",
    "name": "Rexidin",
    "generic": "Chlorhexidine Gluconate",
    "description": "0.2% sample | Mouthwash | Gum infection/plaque control",
    "category": "Antiseptic mouthwash",
    "condition": "Gum disease / oral hygiene",
    "strength": "0.2% sample",
    "dosageForm": "Mouthwash",
    "route": "Oral rinse",
    "brand": "Rexidin",
    "manufacturer": "Indoco Remedies",
    "prescriptionType": "Dentist advised",
    "ageGroup": "Adult/Child as advised",
    "pregnancyCaution": "Yes",
    "allergyCheckRequired": "Yes",
    "procedureOnly": "No",
    "antibioticFlag": "No",
    "otcFlag": "No",
    "showToPatient": "Yes",
    "commonUse": "Gum infection/plaque control",
    "safetyNotes": "Short-term use; may stain teeth/tongue.",
    "sourceUrl": "https://www.1mg.com/search/all?name=rexidin",
    "status": "Active"
  },
  {
    "id": "MED-DENT-0019",
    "name": "Orahex M",
    "generic": "Chlorhexidine + Metronidazole",
    "description": "Gel sample | Gum Gel | Localized gum infection support",
    "category": "Dental gel",
    "condition": "Gum infection",
    "strength": "Gel sample",
    "dosageForm": "Gum Gel",
    "route": "Topical oral",
    "brand": "Orahex M",
    "manufacturer": "Abbott",
    "prescriptionType": "Dentist advised",
    "ageGroup": "Adult/Child as advised",
    "pregnancyCaution": "Yes",
    "allergyCheckRequired": "Yes",
    "procedureOnly": "No",
    "antibioticFlag": "No",
    "otcFlag": "No",
    "showToPatient": "Yes",
    "commonUse": "Localized gum infection support",
    "safetyNotes": "Do not use as substitute for scaling or dental procedure.",
    "sourceUrl": "https://www.1mg.com/generics/chlorhexidine-gluconate-metronidazole-400954",
    "status": "Active"
  },
  {
    "id": "MED-DENT-0020",
    "name": "Metzine",
    "generic": "Metronidazole + Chlorhexidine",
    "description": "Gel sample | Gum Gel | Localized gum infection support",
    "category": "Dental gel",
    "condition": "Gum infection",
    "strength": "Gel sample",
    "dosageForm": "Gum Gel",
    "route": "Topical oral",
    "brand": "Metzine",
    "manufacturer": "Group Pharmaceuticals",
    "prescriptionType": "Dentist advised",
    "ageGroup": "Adult/Child as advised",
    "pregnancyCaution": "Yes",
    "allergyCheckRequired": "Yes",
    "procedureOnly": "No",
    "antibioticFlag": "No",
    "otcFlag": "No",
    "showToPatient": "Yes",
    "commonUse": "Localized gum infection support",
    "safetyNotes": "Dentist-guided local use.",
    "sourceUrl": "https://www.1mg.com/generics/chlorhexidine-gluconate-metronidazole-400954",
    "status": "Active"
  },
  {
    "id": "MED-DENT-0021",
    "name": "Dentonex M",
    "generic": "Metronidazole + Chlorhexidine",
    "description": "Gel sample | Gel | Gum infection support",
    "category": "Dental gel",
    "condition": "Gum infection / bleeding",
    "strength": "Gel sample",
    "dosageForm": "Gel",
    "route": "Topical oral",
    "brand": "Dentonex M",
    "manufacturer": "Nexus India",
    "prescriptionType": "Dentist advised",
    "ageGroup": "Adult/Child as advised",
    "pregnancyCaution": "Yes",
    "allergyCheckRequired": "Yes",
    "procedureOnly": "No",
    "antibioticFlag": "No",
    "otcFlag": "No",
    "showToPatient": "Yes",
    "commonUse": "Gum infection support",
    "safetyNotes": "Need dentist evaluation if bleeding persists.",
    "sourceUrl": "https://www.1mg.com/search/all?name=dentonex%20m",
    "status": "Active"
  },
  {
    "id": "MED-DENT-0022",
    "name": "Mucopain",
    "generic": "Lignocaine / Lidocaine",
    "description": "Gel sample | Oral Gel | Temporary ulcer pain relief",
    "category": "Local anesthetic",
    "condition": "Mouth ulcer",
    "strength": "Gel sample",
    "dosageForm": "Oral Gel",
    "route": "Topical oral",
    "brand": "Mucopain",
    "manufacturer": "ICPA Health Products",
    "prescriptionType": "Dentist advised",
    "ageGroup": "Adult/Child as advised",
    "pregnancyCaution": "Yes",
    "allergyCheckRequired": "Yes",
    "procedureOnly": "No",
    "antibioticFlag": "No",
    "otcFlag": "No",
    "showToPatient": "Yes",
    "commonUse": "Temporary ulcer pain relief",
    "safetyNotes": "Avoid overuse and swallowing excess gel.",
    "sourceUrl": "https://www.1mg.com/search/all?name=mucopain",
    "status": "Active"
  },
  {
    "id": "MED-DENT-0023",
    "name": "Dologel CT",
    "generic": "Choline Salicylate + Lidocaine",
    "description": "Gel sample | Oral Gel | Mouth ulcer pain relief",
    "category": "Ulcer gel",
    "condition": "Mouth ulcer",
    "strength": "Gel sample",
    "dosageForm": "Oral Gel",
    "route": "Topical oral",
    "brand": "Dologel CT",
    "manufacturer": "Dr. Reddy's / marketed variants",
    "prescriptionType": "Dentist advised",
    "ageGroup": "Adult/Child as advised",
    "pregnancyCaution": "Yes",
    "allergyCheckRequired": "Yes",
    "procedureOnly": "No",
    "antibioticFlag": "No",
    "otcFlag": "No",
    "showToPatient": "Yes",
    "commonUse": "Mouth ulcer pain relief",
    "safetyNotes": "Avoid unsupervised use in young children; salicylate caution.",
    "sourceUrl": "https://www.1mg.com/search/all?name=dologel%20ct",
    "status": "Active"
  },
  {
    "id": "MED-DENT-0024",
    "name": "Kenacort Oral Paste",
    "generic": "Triamcinolone Acetonide",
    "description": "0.1% sample | Oral Paste | Inflammatory oral ulcers",
    "category": "Steroid oral paste",
    "condition": "Mouth ulcer",
    "strength": "0.1% sample",
    "dosageForm": "Oral Paste",
    "route": "Topical oral",
    "brand": "Kenacort Oral Paste",
    "manufacturer": "Abbott",
    "prescriptionType": "Rx only",
    "ageGroup": "Adult/Child as advised",
    "pregnancyCaution": "Yes",
    "allergyCheckRequired": "Yes",
    "procedureOnly": "No",
    "antibioticFlag": "No",
    "otcFlag": "No",
    "showToPatient": "Yes",
    "commonUse": "Inflammatory oral ulcers",
    "safetyNotes": "Not for fungal/viral lesions unless dentist/doctor advises.",
    "sourceUrl": "https://www.1mg.com/search/all?name=kenacort%20oral%20paste",
    "status": "Active"
  },
  {
    "id": "MED-DENT-0025",
    "name": "Becosules",
    "generic": "Vitamin B-Complex",
    "description": "Supplement sample | Tablet / Syrup | Supportive care in deficiency",
    "category": "Vitamin supplement",
    "condition": "Mouth ulcer / healing support",
    "strength": "Supplement sample",
    "dosageForm": "Tablet / Syrup",
    "route": "Oral",
    "brand": "Becosules",
    "manufacturer": "Pfizer",
    "prescriptionType": "OTC/Rx",
    "ageGroup": "Adult/Child",
    "pregnancyCaution": "Yes",
    "allergyCheckRequired": "Yes",
    "procedureOnly": "No",
    "antibioticFlag": "No",
    "otcFlag": "Yes",
    "showToPatient": "Yes",
    "commonUse": "Supportive care in deficiency",
    "safetyNotes": "Supplement, not a direct dental cure.",
    "sourceUrl": "https://www.1mg.com/search/all?name=becosules",
    "status": "Active"
  },
  {
    "id": "MED-DENT-0026",
    "name": "Folvite",
    "generic": "Folic Acid",
    "description": "5 mg sample | Tablet | Deficiency support",
    "category": "Supplement",
    "condition": "Mouth ulcer / deficiency",
    "strength": "5 mg sample",
    "dosageForm": "Tablet",
    "route": "Oral",
    "brand": "Folvite",
    "manufacturer": "Pfizer",
    "prescriptionType": "OTC/Rx",
    "ageGroup": "Adult/Child",
    "pregnancyCaution": "Yes",
    "allergyCheckRequired": "Yes",
    "procedureOnly": "No",
    "antibioticFlag": "No",
    "otcFlag": "Yes",
    "showToPatient": "Yes",
    "commonUse": "Deficiency support",
    "safetyNotes": "Use when deficiency or clinician advice exists.",
    "sourceUrl": "https://www.1mg.com/search/all?name=folvite",
    "status": "Active"
  },
  {
    "id": "MED-DENT-0027",
    "name": "Sensodyne Essential Care",
    "generic": "Potassium Nitrate",
    "description": "Toothpaste sample | Toothpaste | Tooth sensitivity",
    "category": "Desensitizing toothpaste",
    "condition": "Tooth sensitivity",
    "strength": "Toothpaste sample",
    "dosageForm": "Toothpaste",
    "route": "Topical oral",
    "brand": "Sensodyne Essential Care",
    "manufacturer": "Haleon / GSK consumer health brand",
    "prescriptionType": "OTC",
    "ageGroup": "Adult/Child as advised",
    "pregnancyCaution": "No",
    "allergyCheckRequired": "Yes",
    "procedureOnly": "No",
    "antibioticFlag": "No",
    "otcFlag": "Yes",
    "showToPatient": "Yes",
    "commonUse": "Tooth sensitivity",
    "safetyNotes": "Sensitivity needs diagnosis if persistent or severe.",
    "sourceUrl": "https://www.sensodyne.in/products.html",
    "status": "Active"
  },
  {
    "id": "MED-DENT-0028",
    "name": "Colgate Sensitive",
    "generic": "Potassium Nitrate",
    "description": "Toothpaste sample | Toothpaste | Tooth sensitivity",
    "category": "Desensitizing toothpaste",
    "condition": "Tooth sensitivity",
    "strength": "Toothpaste sample",
    "dosageForm": "Toothpaste",
    "route": "Topical oral",
    "brand": "Colgate Sensitive",
    "manufacturer": "Colgate-Palmolive",
    "prescriptionType": "OTC",
    "ageGroup": "Adult/Child as advised",
    "pregnancyCaution": "No",
    "allergyCheckRequired": "Yes",
    "procedureOnly": "No",
    "antibioticFlag": "No",
    "otcFlag": "Yes",
    "showToPatient": "Yes",
    "commonUse": "Tooth sensitivity",
    "safetyNotes": "Use as oral-care product; see dentist if pain persists.",
    "sourceUrl": "https://www.1mg.com/otc/colgate-sensitive-anticavity-toothpaste-80gm-each-otc566953",
    "status": "Active"
  },
  {
    "id": "MED-DENT-0029",
    "name": "Colgate Fluoride variants",
    "generic": "Sodium Fluoride",
    "description": "Toothpaste/Gel sample | Toothpaste / Gel / Varnish | Cavity prevention/enamel support",
    "category": "Fluoride product",
    "condition": "Tooth sensitivity / enamel care",
    "strength": "Toothpaste/Gel sample",
    "dosageForm": "Toothpaste / Gel / Varnish",
    "route": "Topical oral",
    "brand": "Colgate Fluoride variants",
    "manufacturer": "Colgate-Palmolive",
    "prescriptionType": "OTC/Dentist use",
    "ageGroup": "Adult/Child as advised",
    "pregnancyCaution": "No",
    "allergyCheckRequired": "Yes",
    "procedureOnly": "No",
    "antibioticFlag": "No",
    "otcFlag": "Yes",
    "showToPatient": "Yes",
    "commonUse": "Cavity prevention/enamel support",
    "safetyNotes": "Avoid swallowing large amounts; dentist for fluoride varnish.",
    "sourceUrl": "https://www.colgate.com/en-in/products/toothpaste",
    "status": "Active"
  },
  {
    "id": "MED-DENT-0030",
    "name": "Fluoritop",
    "generic": "Sodium Fluoride",
    "description": "Varnish sample | Dental Varnish | Professional cavity prevention",
    "category": "Fluoride varnish",
    "condition": "Cavity prevention",
    "strength": "Varnish sample",
    "dosageForm": "Dental Varnish",
    "route": "Topical dental",
    "brand": "Fluoritop",
    "manufacturer": "ICPA Health Products",
    "prescriptionType": "Dentist use",
    "ageGroup": "Adult/Child as advised",
    "pregnancyCaution": "No",
    "allergyCheckRequired": "Yes",
    "procedureOnly": "Yes",
    "antibioticFlag": "No",
    "otcFlag": "No",
    "showToPatient": "No",
    "commonUse": "Professional cavity prevention",
    "safetyNotes": "Procedure-only; applied by dentist.",
    "sourceUrl": "https://www.1mg.com/search/all?name=fluoritop",
    "status": "Active"
  },
  {
    "id": "MED-DENT-0031",
    "name": "GC Tooth Mousse",
    "generic": "CPP-ACP",
    "description": "Cream sample | Tooth Cream | Remineralization support",
    "category": "Remineralizing cream",
    "condition": "Early enamel support",
    "strength": "Cream sample",
    "dosageForm": "Tooth Cream",
    "route": "Topical oral",
    "brand": "GC Tooth Mousse",
    "manufacturer": "GC Corporation",
    "prescriptionType": "Dentist advised",
    "ageGroup": "Adult/Child as advised",
    "pregnancyCaution": "No",
    "allergyCheckRequired": "Yes",
    "procedureOnly": "No",
    "antibioticFlag": "No",
    "otcFlag": "No",
    "showToPatient": "Yes",
    "commonUse": "Remineralization support",
    "safetyNotes": "Avoid if milk protein allergy.",
    "sourceUrl": "https://www.gc.dental/",
    "status": "Active"
  },
  {
    "id": "MED-DENT-0032",
    "name": "Nystatin Oral Suspension",
    "generic": "Nystatin",
    "description": "Suspension sample | Oral Suspension / Mouth Paint | Fungal oral infection",
    "category": "Antifungal",
    "condition": "Oral thrush",
    "strength": "Suspension sample",
    "dosageForm": "Oral Suspension / Mouth Paint",
    "route": "Oral/topical",
    "brand": "Nystatin Oral Suspension",
    "manufacturer": "Various",
    "prescriptionType": "Rx",
    "ageGroup": "Adult/Child",
    "pregnancyCaution": "Yes",
    "allergyCheckRequired": "Yes",
    "procedureOnly": "No",
    "antibioticFlag": "No",
    "otcFlag": "No",
    "showToPatient": "Yes",
    "commonUse": "Fungal oral infection",
    "safetyNotes": "Confirm fungal infection before use.",
    "sourceUrl": "https://www.1mg.com/search/all?name=nystatin%20oral%20suspension",
    "status": "Active"
  },
  {
    "id": "MED-DENT-0033",
    "name": "Candid Mouth Paint",
    "generic": "Clotrimazole",
    "description": "Mouth paint sample | Mouth Paint / Lozenges | Fungal oral infection",
    "category": "Antifungal",
    "condition": "Oral thrush",
    "strength": "Mouth paint sample",
    "dosageForm": "Mouth Paint / Lozenges",
    "route": "Topical oral",
    "brand": "Candid Mouth Paint",
    "manufacturer": "Glenmark",
    "prescriptionType": "Rx/OTC depends",
    "ageGroup": "Adult/Child as advised",
    "pregnancyCaution": "Yes",
    "allergyCheckRequired": "Yes",
    "procedureOnly": "No",
    "antibioticFlag": "No",
    "otcFlag": "No",
    "showToPatient": "Yes",
    "commonUse": "Fungal oral infection",
    "safetyNotes": "Check diagnosis and recurrence causes like diabetes/denture hygiene.",
    "sourceUrl": "https://www.1mg.com/search/all?name=candid%20mouth%20paint",
    "status": "Active"
  },
  {
    "id": "MED-DENT-0034",
    "name": "Daktarin Oral Gel",
    "generic": "Miconazole",
    "description": "Oral gel sample | Oral Gel | Fungal oral infection",
    "category": "Antifungal",
    "condition": "Oral thrush",
    "strength": "Oral gel sample",
    "dosageForm": "Oral Gel",
    "route": "Topical oral",
    "brand": "Daktarin Oral Gel",
    "manufacturer": "Janssen / Johnson & Johnson brand",
    "prescriptionType": "Rx",
    "ageGroup": "Adult/Child as advised",
    "pregnancyCaution": "Yes",
    "allergyCheckRequired": "Yes",
    "procedureOnly": "No",
    "antibioticFlag": "No",
    "otcFlag": "No",
    "showToPatient": "Yes",
    "commonUse": "Fungal oral infection",
    "safetyNotes": "Drug interaction caution, especially anticoagulants.",
    "sourceUrl": "https://www.1mg.com/search/all?name=daktarin%20oral%20gel",
    "status": "Active"
  },
  {
    "id": "MED-DENT-0035",
    "name": "Forcan",
    "generic": "Fluconazole",
    "description": "150 mg sample | Tablet / Suspension | Systemic fungal infection",
    "category": "Antifungal",
    "condition": "Severe fungal infection",
    "strength": "150 mg sample",
    "dosageForm": "Tablet / Suspension",
    "route": "Oral",
    "brand": "Forcan",
    "manufacturer": "Cipla",
    "prescriptionType": "Rx only",
    "ageGroup": "Adult/Child as advised",
    "pregnancyCaution": "Yes",
    "allergyCheckRequired": "Yes",
    "procedureOnly": "No",
    "antibioticFlag": "No",
    "otcFlag": "No",
    "showToPatient": "Yes",
    "commonUse": "Systemic fungal infection",
    "safetyNotes": "Doctor/dentist guided; liver and interaction cautions.",
    "sourceUrl": "https://www.1mg.com/search/all?name=forcan",
    "status": "Active"
  },
  {
    "id": "MED-DENT-0036",
    "name": "Acivir",
    "generic": "Acyclovir",
    "description": "400 mg sample | Tablet / Cream | Viral lesions/cold sores",
    "category": "Antiviral",
    "condition": "Cold sore / viral lesion",
    "strength": "400 mg sample",
    "dosageForm": "Tablet / Cream",
    "route": "Oral/Topical",
    "brand": "Acivir",
    "manufacturer": "Cipla",
    "prescriptionType": "Rx",
    "ageGroup": "Adult/Child as advised",
    "pregnancyCaution": "Yes",
    "allergyCheckRequired": "Yes",
    "procedureOnly": "No",
    "antibioticFlag": "No",
    "otcFlag": "No",
    "showToPatient": "Yes",
    "commonUse": "Viral lesions/cold sores",
    "safetyNotes": "Best started early; only for viral lesions.",
    "sourceUrl": "https://www.1mg.com/search/all?name=acivir",
    "status": "Active"
  },
  {
    "id": "MED-DENT-0037",
    "name": "Zovirax",
    "generic": "Acyclovir",
    "description": "Cream/tablet sample | Cream / Tablet | Viral lesions/cold sores",
    "category": "Antiviral",
    "condition": "Cold sore / viral lesion",
    "strength": "Cream/tablet sample",
    "dosageForm": "Cream / Tablet",
    "route": "Topical/Oral",
    "brand": "Zovirax",
    "manufacturer": "GSK",
    "prescriptionType": "Rx/OTC depends",
    "ageGroup": "Adult/Child as advised",
    "pregnancyCaution": "Yes",
    "allergyCheckRequired": "Yes",
    "procedureOnly": "No",
    "antibioticFlag": "No",
    "otcFlag": "No",
    "showToPatient": "Yes",
    "commonUse": "Viral lesions/cold sores",
    "safetyNotes": "Confirm viral cause before use.",
    "sourceUrl": "https://www.1mg.com/search/all?name=zovirax",
    "status": "Active"
  },
  {
    "id": "MED-DENT-0038",
    "name": "Hexidine / Rexidin",
    "generic": "Chlorhexidine",
    "description": "0.2% sample | Mouthwash | Post-surgery oral hygiene",
    "category": "Antiseptic rinse",
    "condition": "Post-extraction care",
    "strength": "0.2% sample",
    "dosageForm": "Mouthwash",
    "route": "Oral rinse",
    "brand": "Hexidine / Rexidin",
    "manufacturer": "ICPA / Indoco",
    "prescriptionType": "Dentist advised",
    "ageGroup": "Adult/Child as advised",
    "pregnancyCaution": "Yes",
    "allergyCheckRequired": "Yes",
    "procedureOnly": "No",
    "antibioticFlag": "No",
    "otcFlag": "No",
    "showToPatient": "Yes",
    "commonUse": "Post-surgery oral hygiene",
    "safetyNotes": "Usually after dentist instruction; do not rinse aggressively immediately after extraction.",
    "sourceUrl": "https://www.1mg.com/search/all?name=chlorhexidine%20mouthwash",
    "status": "Active"
  },
  {
    "id": "MED-DENT-0039",
    "name": "Dolo / Brufen",
    "generic": "Paracetamol / Ibuprofen",
    "description": "Sample | Tablet | Post-procedure pain",
    "category": "Painkiller",
    "condition": "Post-extraction pain",
    "strength": "Sample",
    "dosageForm": "Tablet",
    "route": "Oral",
    "brand": "Dolo / Brufen",
    "manufacturer": "Micro Labs / Abbott",
    "prescriptionType": "As advised",
    "ageGroup": "Adult/Child as advised",
    "pregnancyCaution": "Yes",
    "allergyCheckRequired": "Yes",
    "procedureOnly": "No",
    "antibioticFlag": "No",
    "otcFlag": "Yes",
    "showToPatient": "Yes",
    "commonUse": "Post-procedure pain",
    "safetyNotes": "Avoid aspirin after extraction unless doctor advised due bleeding risk.",
    "sourceUrl": "https://www.1mg.com/search/all?name=paracetamol%20ibuprofen",
    "status": "Active"
  },
  {
    "id": "MED-DENT-0040",
    "name": "Alveogyl",
    "generic": "Eugenol-based dressing",
    "description": "Dressing sample | Dental Dressing | Dry socket dressing",
    "category": "Dental dressing",
    "condition": "Dry socket / post extraction",
    "strength": "Dressing sample",
    "dosageForm": "Dental Dressing",
    "route": "Dental application",
    "brand": "Alveogyl",
    "manufacturer": "Septodont",
    "prescriptionType": "Dentist use only",
    "ageGroup": "Adult",
    "pregnancyCaution": "Yes",
    "allergyCheckRequired": "Yes",
    "procedureOnly": "Yes",
    "antibioticFlag": "No",
    "otcFlag": "No",
    "showToPatient": "No",
    "commonUse": "Dry socket dressing",
    "safetyNotes": "Procedure-only; applied by dentist.",
    "sourceUrl": "https://www.septodont.co.uk/products/alveogyl/",
    "status": "Active"
  },
  {
    "id": "MED-DENT-0041",
    "name": "Listerine / Hexidine variants",
    "generic": "Chlorhexidine / Cetylpyridinium Chloride",
    "description": "Mouthwash sample | Mouthwash | Oral hygiene/bad breath support",
    "category": "Mouthwash",
    "condition": "Bad breath / halitosis",
    "strength": "Mouthwash sample",
    "dosageForm": "Mouthwash",
    "route": "Oral rinse",
    "brand": "Listerine / Hexidine variants",
    "manufacturer": "Kenvue / ICPA etc.",
    "prescriptionType": "OTC/Dentist advised",
    "ageGroup": "Adult/Child as advised",
    "pregnancyCaution": "Yes",
    "allergyCheckRequired": "Yes",
    "procedureOnly": "No",
    "antibioticFlag": "No",
    "otcFlag": "Yes",
    "showToPatient": "Yes",
    "commonUse": "Oral hygiene/bad breath support",
    "safetyNotes": "Treat root cause: gum disease, cavity, tongue coating, dry mouth.",
    "sourceUrl": "https://www.listerine.in/",
    "status": "Active"
  },
  {
    "id": "MED-DENT-0042",
    "name": "Betadine Gargle",
    "generic": "Povidone Iodine",
    "description": "Gargle sample | Gargle / Mouthwash | Short-term antiseptic gargle",
    "category": "Antiseptic gargle",
    "condition": "Plaque control / antiseptic gargle",
    "strength": "Gargle sample",
    "dosageForm": "Gargle / Mouthwash",
    "route": "Oral rinse",
    "brand": "Betadine Gargle",
    "manufacturer": "Win-Medicare / Mundipharma brand",
    "prescriptionType": "OTC/Dentist advised",
    "ageGroup": "Adult/Child as advised",
    "pregnancyCaution": "Yes",
    "allergyCheckRequired": "Yes",
    "procedureOnly": "No",
    "antibioticFlag": "No",
    "otcFlag": "Yes",
    "showToPatient": "Yes",
    "commonUse": "Short-term antiseptic gargle",
    "safetyNotes": "Avoid if iodine allergy/thyroid issues unless doctor advises.",
    "sourceUrl": "https://www.betadine.co.in/",
    "status": "Active"
  },
  {
    "id": "MED-DENT-0043",
    "name": "Tantum",
    "generic": "Benzydamine",
    "description": "Mouthwash sample | Mouthwash | Mouth/throat inflammation pain relief",
    "category": "Anti-inflammatory rinse",
    "condition": "Painful oral inflammation",
    "strength": "Mouthwash sample",
    "dosageForm": "Mouthwash",
    "route": "Oral rinse",
    "brand": "Tantum",
    "manufacturer": "Common international brand",
    "prescriptionType": "Rx/OTC depends",
    "ageGroup": "Adult/Child as advised",
    "pregnancyCaution": "Yes",
    "allergyCheckRequired": "Yes",
    "procedureOnly": "No",
    "antibioticFlag": "No",
    "otcFlag": "No",
    "showToPatient": "Yes",
    "commonUse": "Mouth/throat inflammation pain relief",
    "safetyNotes": "Symptomatic relief; evaluate persistent lesions.",
    "sourceUrl": "https://www.1mg.com/search/all?name=benzydamine%20mouthwash",
    "status": "Active"
  },
  {
    "id": "MED-DENT-0044",
    "name": "Lignox",
    "generic": "Lignocaine with Adrenaline",
    "description": "2% sample | Injection | Dental procedure anesthesia",
    "category": "Local anesthetic",
    "condition": "Local dental anesthesia",
    "strength": "2% sample",
    "dosageForm": "Injection",
    "route": "Injection",
    "brand": "Lignox",
    "manufacturer": "Indoco Remedies",
    "prescriptionType": "Dentist use only",
    "ageGroup": "Adult/Child as advised",
    "pregnancyCaution": "Yes",
    "allergyCheckRequired": "Yes",
    "procedureOnly": "Yes",
    "antibioticFlag": "No",
    "otcFlag": "No",
    "showToPatient": "No",
    "commonUse": "Dental procedure anesthesia",
    "safetyNotes": "Procedure-only; check allergy, cardiac history, dose limits.",
    "sourceUrl": "https://www.1mg.com/search/all?name=lignox",
    "status": "Active"
  },
  {
    "id": "MED-DENT-0045",
    "name": "Septanest",
    "generic": "Articaine with Adrenaline",
    "description": "4% sample cartridge | Injection Cartridge | Dental procedure anesthesia",
    "category": "Local anesthetic",
    "condition": "Dental procedure anesthesia",
    "strength": "4% sample cartridge",
    "dosageForm": "Injection Cartridge",
    "route": "Injection",
    "brand": "Septanest",
    "manufacturer": "Septodont",
    "prescriptionType": "Dentist use only",
    "ageGroup": "Adult/Child as advised",
    "pregnancyCaution": "Yes",
    "allergyCheckRequired": "Yes",
    "procedureOnly": "Yes",
    "antibioticFlag": "No",
    "otcFlag": "No",
    "showToPatient": "No",
    "commonUse": "Dental procedure anesthesia",
    "safetyNotes": "Procedure-only; dentist-administered.",
    "sourceUrl": "https://www.septodont.co.uk/products/septanest/",
    "status": "Active"
  }
];
